In [1]:
import torch
import transformers
from transformers import pipeline

In [2]:
pip install torch

Requirement already satisfied: torch in c:\users\inspector\anaconda3\lib\site-packages (2.13.0)
Requirement already satisfied: filelock in c:\users\inspector\anaconda3\lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\inspector\anaconda3\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\inspector\anaconda3\lib\site-packages (from torch) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\inspector\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\inspector\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\inspector\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\inspector\anaconda3\lib\site-packages (from torch) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\inspector\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\inspector\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [24]:
sentiment_pipline=pipeline('sentiment-analysis')

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [28]:
sentence_1 = "i had a great time at the movie it was really funny"
sentence_2 = "i had a great time at the movie but the parking was terrible"
sentence_3 = "i had a great time at the movie but the parking wasn't great"
sentence_4 = "i went to see a movie"

In [29]:
score=sentiment_pipline(sentence_1)
print(score)

[{'label': 'POSITIVE', 'score': 0.9998176693916321}]

In [10]:
import pandas as pd #for practice
pd.DataFrame(score)

      label     score
0  POSITIVE  0.999818

In [17]:
print(sentence_2)
score_2=sentiment_pipline(sentence_2)
pd.DataFrame(score_2)

i had a great time at the movie but the parking was terrible

      label     score
0  NEGATIVE  0.997746

In [18]:
specific_model = pipeline("sentiment-analysis", model="finiteautomata/bertweet-base-sentiment-analysis")

config.json:   0%|          | 0.00/949 [00:00<?, ?B/s]

C:\Users\Inspector\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Inspector\.cache\huggingface\hub\models--finiteautomata--bertweet-base-sentiment-analysis. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  540MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/338 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  540MB

model.safetensors: downloading bytes:           |  0.00B

vocab.txt:   0%|          | 0.00/843k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.08M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/167 [00:00<?, ?B/s]

[transformers] emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 142, in _event_pipe
    event_pipe = self._local.event_pipe
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 2065, in excepthook
    self.showtraceback((etype, value, tb), tb_offset=0)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 2179, in showtraceback
    self._showtraceback(etype, value, stb)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 553, in _showtraceback
    sys.stdout.flush()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 604, in flush
    self.pub_thread.schedule(self._flush)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self, socket_type, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        ctx_or_socket,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        copy_threshold=copy_threshold,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
zmq.error.ZMQError: Too many open files

Original exception was:
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 142, in _event_pipe
    event_pipe = self._local.event_pipe
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\tqdm\notebook.py", line 262, in update
    return super().update(n=n)
           ~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\tqdm\std.py", line 1242, in update
    self.refresh(lock_args=self.lock_args)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\tqdm\std.py", line 1347, in refresh
    self.display()
    ~~~~~~~~~~~~^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\tqdm\notebook.py", line 157, in display
    pbar.value = self.n
    ^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\traitlets\traitlets.py", line 716, in __set__
    self.set(obj, value)
    ~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\traitlets\traitlets.py", line 706, in set
    obj._notify_trait(self.name, old_value, new_value)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\traitlets\traitlets.py", line 1513, in _notify_trait
    self.notify_change(
    ~~~~~~~~~~~~~~~~~~^
        Bunch(
        ^^^^^^
    ...<5 lines>...
        )
        ^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py", line 700, in notify_change
    self.send_state(key=name)
    ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py", line 586, in send_state
    self._send(msg, buffers=buffers)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py", line 825, in _send
    self.comm.send(data=msg, buffers=buffers)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\comm\base_comm.py", line 147, in send
    self.publish_msg(
    ~~~~~~~~~~~~~~~~^
        "comm_msg",
        ^^^^^^^^^^^
    ...<2 lines>...
        buffers=buffers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\comm\comm.py", line 37, in publish_msg
    self.kernel.session.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        self.kernel.iopub_socket,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        buffers=buffers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\jupyter_client\session.py", line 863, in send
    stream.send_multipart(to_send, copy=copy)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 346, in send_multipart
    return self.io_thread.send_multipart(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 276, in send_multipart
    self.schedule(lambda: self._really_send(*args, **kwargs))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self, socket_type, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        ctx_or_socket,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        copy_threshold=copy_threshold,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
zmq.error.ZMQError: Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 142, in _event_pipe
    event_pipe = self._local.event_pipe
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\huggingface_hub\utils\_xet_progress_reporting.py", line 153, in update_progress
    _update_transfer_bar(self.transfer_bar, transfer_inc)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\huggingface_hub\utils\_xet_progress_reporting.py", line 35, in _update_transfer_bar
    bar.update(inc)
    ~~~~~~~~~~^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\tqdm\notebook.py", line 267, in update
    self.disp(bar_style='danger')
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\tqdm\notebook.py", line 171, in display
    rtext.value = right
    ^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\traitlets\traitlets.py", line 716, in __set__
    self.set(obj, value)
    ~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\traitlets\traitlets.py", line 706, in set
    obj._notify_trait(self.name, old_value, new_value)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\traitlets\traitlets.py", line 1513, in _notify_trait
    self.notify_change(
    ~~~~~~~~~~~~~~~~~~^
        Bunch(
        ^^^^^^
    ...<5 lines>...
        )
        ^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py", line 700, in notify_change
    self.send_state(key=name)
    ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py", line 586, in send_state
    self._send(msg, buffers=buffers)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipywidgets\widgets\widget.py", line 825, in _send
    self.comm.send(data=msg, buffers=buffers)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\comm\base_comm.py", line 147, in send
    self.publish_msg(
    ~~~~~~~~~~~~~~~~^
        "comm_msg",
        ^^^^^^^^^^^
    ...<2 lines>...
        buffers=buffers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\comm\comm.py", line 37, in publish_msg
    self.kernel.session.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        self.kernel.iopub_socket,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        buffers=buffers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\jupyter_client\session.py", line 863, in send
    stream.send_multipart(to_send, copy=copy)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 346, in send_multipart
    return self.io_thread.send_multipart(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 276, in send_multipart
    self.schedule(lambda: self._really_send(*args, **kwargs))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self, socket_type, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        ctx_or_socket,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        copy_threshold=copy_threshold,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
zmq.error.ZMQError: Too many open files

In [20]:
!pip3 install emoji==0.6.0

Collecting emoji==0.6.0

  DEPRECATION: Building 'emoji' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'emoji'. Discussion can be found at https://github.com/pypa/pip/issues/6334Exception in thread Thread-1020 (stderr_read):
Exception in thread Thread-1019 (stdout_read):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 142, in _event_pipe
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 142, in _event_pipe
    event_pipe = self._local.event_pipe
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\IPython\utils\_process_win32.py", line 81, in stdout_read
    print(line, file=sys.stdout)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 694, in write
    self._schedule_flush()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 590, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self, socket_type, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        ctx_or_socket,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        copy_threshold=copy_threshold,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
zmq.error.ZMQError: Too many open files
Exception in threading.excepthook:
Exception ignored in thread started by <bound method Thread._bootstrap of <Thread(Thread-1019 (stdout_read), started 11928)>>:
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1014, in _bootstrap
    event_pipe = self._local.event_pipe
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1043, in _bootstrap_inner
    self._bootstrap_inner()
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1045, in _bootstrap_inner
    self._invoke_excepthook(self)
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1302, in invoke_excepthook
    self.run()
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 766, in run_closure
    local_print("Exception in threading.excepthook:",
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 604, in flush
    _threading_Thread_run(self)
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 994, in run
    self.pub_thread.schedule(self._flush)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\IPython\utils\_process_win32.py", line 86, in stderr_read
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    print(line, file=sys.stderr)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 694, in write
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    self._schedule_flush()
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 590, in _schedule_flush
    super().__init__(
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
    self.pub_thread.schedule(_schedule_in_thread)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
zmq.error.ZMQError: Too many open files
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 604, in flush
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    self.pub_thread.schedule(self._flush)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    super().__init__(
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
    self._event_pipe.send(b"")
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
zmq.error.ZMQError: Too many open files
Exception in threading.excepthook:
Exception ignored in thread started by <bound method Thread._bootstrap of <Thread(Thread-1020 (stderr_read), started 13796)>>:
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1014, in _bootstrap
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    self._bootstrap_inner()
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1045, in _bootstrap_inner
    self._invoke_excepthook(self)
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1302, in invoke_excepthook
    super().__init__(
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
    local_print("Exception in threading.excepthook:",
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 604, in flush
zmq.error.ZMQError: Too many open files
    self.pub_thread.schedule(self._flush)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    super().__init__(
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
zmq.error.ZMQError: Too many open files
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 604, in flush
    self.pub_thread.schedule(self._flush)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    super().__init__(
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
zmq.error.ZMQError: Too many open files

In [21]:
!pip install emoji

Exception in thread Exception in threading.excepthook:
Exception ignored in thread started by <bound method Thread._bootstrap of <Thread(Thread-1023 (stdout_read), started 8032)>>:
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1045, in _bootstrap_inner
    self._invoke_excepthook(self)
  File "C:\Users\Inspector\anaconda3\Lib\threading.py", line 1302, in invoke_excepthook
    local_print("Exception in threading.excepthook:",
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 604, in flush
    self.pub_thread.schedule(self._flush)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    super().__init__(
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
zmq.error.ZMQError: Too many open files
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
Traceback (most recent call last):
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 604, in flush
    self.pub_thread.schedule(self._flush)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\ipykernel\iostream.py", line 146, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\context.py", line 354, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
  File "C:\Users\Inspector\anaconda3\Lib\site-packages\zmq\sugar\socket.py", line 156, in __init__
    super().__init__(
  File "_zmq.py", line 690, in zmq.backend.cython._zmq.Socket.__init__
zmq.error.ZMQError: Too many open files

Requirement already satisfied: emoji in c:\users\inspector\anaconda3\lib\site-packages (0.6.0)

In [1]:
from transformers import pipeline

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="finiteautomata/bertweet-base-sentiment-analysis"
)

result = sentiment_pipeline("I love this movie!")

print(result)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  540MB

model.safetensors: downloading bytes:           |  0.00B

[{'label': 'POS', 'score': 0.9926134347915649}]

C:\Users\Inspector\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Inspector\.cache\huggingface\hub\models--finiteautomata--bertweet-base-sentiment-analysis. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [6]:

specific_model = pipeline("sentiment-analysis", model="finiteautomata/bertweet-base-sentiment-analysis")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [7]:
print(sentence_1)
specific_model(sentence_1)

i had a great time at the movie it was really funny

[{'label': 'POS', 'score': 0.9923344254493713}]

In [12]:

specific_model(input("enter the sentence"))

i had a great time at the movie it was really funny

enter the sentence To is a bad day i am very sad

[{'label': 'NEG', 'score': 0.979832649230957}]

In [16]:

import pandas as pd
score_2=specific_model("To day is tuesday")

In [17]:
pd.DataFrame(score_2)

  label     score
0   NEU  0.954973

In [19]:
specific_model('I love this movie 😍')

[{'label': 'POS', 'score': 0.9922086000442505}]